version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - "./:/usr/app"
        depends_on:
            - "db"
        environment:
            CHOKIDAR_USEPOLLING: "true"
            MYSQL_HOST: "db"
            MYSQL_PORT: 3306
            MYSQL_USERNAME: "test"
            MYSQL_PASSWORD: "test"
            MYSQL_DATABASE: "chat-api"
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: abc12345
            MYSQL_DATABASE: chat-api
            MYSQL_USER: test
            MYSQL_PASSWORD: test
