version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.secret
        ports:
            - "3000:3000"
        volumes:
            - "./:/usr/app"
        depends_on:
            - "db"
    db:
        image: mongo
        restart: always
