version: "3"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.secret
        ports:
            - "3000:3000"
        volumes:
            - "./:/usr/app"
        depends_on:
            - "db"
        environment:
            CHOKIDAR_USEPOLLING: "true"
            CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
            CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
            JWT_SECRET: "YOUR_JWT_SECRET"
            REDIRECT_URI: "http://localhost:3000/auth/redirect"

    db:
        image: mongo
        restart: always
